In [56]:
import pandas as pd
import numpy as np
import random

df = pd.read_csv('spotify_songs.csv')

In [ ]:
def consultar_canciones(cantidad=10):
    if cantidad is None:
        cantidad = 10
    return df[["track_name", "track_artist", "playlist_genre", "track_popularity"]].sort_values(
        by="track_popularity",
        ascending=False
    ).head(cantidad)

consultar_canciones(2)

         track_name track_artist playlist_genre  track_popularity
20091  Dance Monkey  Tones and I          latin               100

In [58]:
def buscar_canciones_genero(genero, cantidad=10):
    resultado = df[df["playlist_genre"] == genero]
    
    # return resultado[["track_id", "track_name", "track_artist", "playlist_genre", "track_popularity"]].head(cantidad)
    return resultado[["track_id", "track_name", "track_artist", "playlist_genre", "track_popularity"]].sort_values(
        by = "track_popularity", ascending=False
    ).head(cantidad)

                                                                                                              
buscar_canciones_genero("rock", 10)

,track_id,track_name,track_artist,playlist_genre,track_popularity
13900,2Fxmhks0bxGSBdJ92vM42m,bad guy,Billie Eilish,rock,95
14382,3KkXRkHbMCARz0aVfEt68P,Sunflower - Spider-Man: Into the Spider-Verse,Post Malone,rock,88
14539,6K4t31amVTZDgR3sKmwUJJ,The Less I Know The Better,Tame Impala,rock,85
11798,6K4t31amVTZDgR3sKmwUJJ,The Less I Know The Better,Tame Impala,rock,85
12109,4u7EnebtmKWzUH433cf5Qv,Bohemian Rhapsody - 2011 Mix,Queen,rock,84
14433,6WkJ2OK163XXS2oARUC9JM,Dancin (feat. Luvli) - Krono Remix,Aaron Smith,rock,84
11742,08mG3Y1vljYA6bvDt4Wqkj,Back In Black,AC/DC,rock,83
12339,08mG3Y1vljYA6bvDt4Wqkj,Back In Black,AC/DC,rock,83
13778,60a0Rd6pjrkxjPbaKzXjfq,In the End,Linkin Park,rock,83
12142,5T8EDUDqKcs6OSOwEsfqG7,Don't Stop Me Now - 2011 Mix,Queen,rock,83

In [59]:
def buscar_canciones_bailables(cantidad=10):
    
    # return resultado[["track_id", "track_name", "track_artist", "playlist_genre", "track_popularity"]].head(cantidad)
    return df[["track_id", "track_name", "track_artist", "playlist_genre", "track_popularity"]].sort_values(
        by = "8", ascending=False
    ).head(cantidad)

                                                                                                              
buscar_canciones_bailables(10)

KeyError: '8'

In [ ]:
def buscar_canciones_genero(genero, cantidad=10):
    resultado = df[df["playlist_genre"] == genero]
    
    # return resultado[["track_id", "track_name", "track_artist", "playlist_genre", "track_popularity"]].head(cantidad)
    return resultado[["track_id", "track_name", "track_artist", "playlist_genre", "track_popularity"]].sort_values(
        by = "track_popularity", ascending=False
    ).head(cantidad)

                                                                                                              
buscar_canciones_genero("rock", 10)

,track_id,track_name,track_artist,playlist_genre,track_popularity
13900,2Fxmhks0bxGSBdJ92vM42m,bad guy,Billie Eilish,rock,95
14382,3KkXRkHbMCARz0aVfEt68P,Sunflower - Spider-Man: Into the Spider-Verse,Post Malone,rock,88
14539,6K4t31amVTZDgR3sKmwUJJ,The Less I Know The Better,Tame Impala,rock,85
11798,6K4t31amVTZDgR3sKmwUJJ,The Less I Know The Better,Tame Impala,rock,85
12109,4u7EnebtmKWzUH433cf5Qv,Bohemian Rhapsody - 2011 Mix,Queen,rock,84
14433,6WkJ2OK163XXS2oARUC9JM,Dancin (feat. Luvli) - Krono Remix,Aaron Smith,rock,84
11742,08mG3Y1vljYA6bvDt4Wqkj,Back In Black,AC/DC,rock,83
12339,08mG3Y1vljYA6bvDt4Wqkj,Back In Black,AC/DC,rock,83
13778,60a0Rd6pjrkxjPbaKzXjfq,In the End,Linkin Park,rock,83
12142,5T8EDUDqKcs6OSOwEsfqG7,Don't Stop Me Now - 2011 Mix,Queen,rock,83

In [ ]:
def canciones_mas_populares(cantidad=10):
    return df[
        ["track_name", "track_artist", "playlist_genre", "track_popularity"]
    ].sort_values(
        by="track_popularity",
        ascending=False
    ).head(cantidad)

canciones_mas_populares(10)

,track_name,track_artist,playlist_genre,duration_ms
21327,47 - Remix,Anuel AA,latin,517810
11770,Kashmir - 2012 Remaster,Led Zeppelin,rock,517125
12391,Kashmir - 2012 Remaster,Led Zeppelin,rock,517125
12379,American Pie,Don McLean,rock,516893
20643,Jam On It (Re-Recorded Version),Newcleus,latin,516760
11919,Roundabout - 2008 Remaster,Yes,rock,515960
13556,American Pie,Don McLean,rock,515867
11914,American Pie,Don McLean,rock,515867
31131,Come as You Are,V-Sag,edm,515703
31660,Summer Groove,The Joneses,edm,515680

In [ ]:
def crear_playlist(nombre):
    playlist = {
        "nombre": nombre,
        "canciones": []
    }

    return playlist

crear_playlist("Gym")

{'nombre': 'Gym', 'canciones': []}

In [ ]:
def agregar_cancion(playlist, id_cancion):
    res = df[df["track_id"] == id_cancion]

    if res.empty:
        print("Cancion no encontrada")
        return playlist

    cancion = res.iloc[0]

    playlist["canciones"].append({
        "track_id": cancion["track_id"],
        "track_name": cancion["track_name"],
        "track_artist": cancion["track_artist"]
    })
    
    return playlist

agregar_cancion(crear_playlist("Gym"), "7o2CTH4ctstm8TNelqjb51")

{'nombre': 'Gym',
 'canciones': [{'track_id': '7o2CTH4ctstm8TNelqjb51',
   'track_name': "Sweet Child O' Mine",
   'track_artist': "Guns N' Roses"}]}

In [ ]:
def consultar_playlist(playlist):
    print(f"Playlist: {playlist['nombre']}")
    print(f"Total de canciones: {len(playlist['canciones'])}")
    
    for i, cancion in enumerate(playlist["canciones"], 1):
        print(f"{i}. {cancion['track_name']} - {cancion['track_artist']}")

consultar_playlist(agregar_cancion(crear_playlist("Gym"), "7o2CTH4ctstm8TNelqjb51"))

Playlist: Gym
Total de canciones: 1
1. Sweet Child O' Mine - Guns N' Roses

In [ ]:
def eliminar_cancion(playlist, id_cancion):
    for cancion in playlist["canciones"]:
        if cancion["track_id"] == id_cancion:
            playlist["canciones"].remove(cancion)

    return playlist


playlist =crear_playlist("Gym")

consultar_playlist(playlist)

agregar_cancion(playlist, "7o2CTH4ctstm8TNelqjb51")
agregar_cancion(playlist, "22TOCwH0z9Mcwoa1tfQbro")
agregar_cancion(playlist, "5wO14EzcJEdnaDRmI35PEP")

consultar_playlist(playlist)

eliminar_cancion(playlist, "7o2CTH4ctstm8TNelqjb51")

consultar_playlist(playlist)

Playlist: Gym
Total de canciones: 0
Playlist: Gym
Total de canciones: 3
1. Sweet Child O' Mine - Guns N' Roses
2. Heart Of The Country - Paul McCartney
3. Grow Old With Me - John Lennon
Playlist: Gym
Total de canciones: 2
1. Heart Of The Country - Paul McCartney
2. Grow Old With Me - John Lennon